package io.sharedstreets.matcher.input;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ingest.proto

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ingest.proto

public final class Ingest {
  private Ingest() {}
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EventDataOrBuilder extends
          // @@protoc_insertion_point(interface_extends:EventData)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string eventType = 1;</code>
     */
    String getEventType();
    /**
     * <code>string eventType = 1;</code>
     */
    com.google.protobuf.ByteString
    getEventTypeBytes();

    /**
     * <code>double eventValue = 2;</code>
     */
    double getEventValue();
  }
  /**
   * Protobuf type {@code EventData}
   */
  public  static final class EventData extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:EventData)
          EventDataOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use EventData.newBuilder() to construct.
    private EventData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EventData() {
      eventType_ = "";
      eventValue_ = 0D;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EventData(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                      input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              eventType_ = s;
              break;
            }
            case 17: {

              eventValue_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return Ingest.internal_static_EventData_descriptor;
    }

    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
      return Ingest.internal_static_EventData_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      Ingest.EventData.class, Ingest.EventData.Builder.class);
    }

    public static final int EVENTTYPE_FIELD_NUMBER = 1;
    private volatile Object eventType_;
    /**
     * <code>string eventType = 1;</code>
     */
    public String getEventType() {
      Object ref = eventType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        eventType_ = s;
        return s;
      }
    }
    /**
     * <code>string eventType = 1;</code>
     */
    public com.google.protobuf.ByteString
    getEventTypeBytes() {
      Object ref = eventType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        eventType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENTVALUE_FIELD_NUMBER = 2;
    private double eventValue_;
    /**
     * <code>double eventValue = 2;</code>
     */
    public double getEventValue() {
      return eventValue_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (!getEventTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, eventType_);
      }
      if (eventValue_ != 0D) {
        output.writeDouble(2, eventValue_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getEventTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, eventType_);
      }
      if (eventValue_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
                .computeDoubleSize(2, eventValue_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof Ingest.EventData)) {
        return super.equals(obj);
      }
      Ingest.EventData other = (Ingest.EventData) obj;

      boolean result = true;
      result = result && getEventType()
              .equals(other.getEventType());
      result = result && (
              Double.doubleToLongBits(getEventValue())
                      == Double.doubleToLongBits(
                      other.getEventValue()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EVENTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getEventType().hashCode();
      hash = (37 * hash) + EVENTVALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              Double.doubleToLongBits(getEventValue()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Ingest.EventData parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Ingest.EventData parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Ingest.EventData parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Ingest.EventData parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Ingest.EventData parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Ingest.EventData parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Ingest.EventData parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static Ingest.EventData parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Ingest.EventData parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }
    public static Ingest.EventData parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Ingest.EventData parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static Ingest.EventData parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Ingest.EventData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code EventData}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:EventData)
            Ingest.EventDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return Ingest.internal_static_EventData_descriptor;
      }

      protected FieldAccessorTable
      internalGetFieldAccessorTable() {
        return Ingest.internal_static_EventData_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        Ingest.EventData.class, Ingest.EventData.Builder.class);
      }

      // Construct using Ingest.EventData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        eventType_ = "";

        eventValue_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return Ingest.internal_static_EventData_descriptor;
      }

      public Ingest.EventData getDefaultInstanceForType() {
        return Ingest.EventData.getDefaultInstance();
      }

      public Ingest.EventData build() {
        Ingest.EventData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Ingest.EventData buildPartial() {
        Ingest.EventData result = new Ingest.EventData(this);
        result.eventType_ = eventType_;
        result.eventValue_ = eventValue_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Ingest.EventData) {
          return mergeFrom((Ingest.EventData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Ingest.EventData other) {
        if (other == Ingest.EventData.getDefaultInstance()) return this;
        if (!other.getEventType().isEmpty()) {
          eventType_ = other.eventType_;
          onChanged();
        }
        if (other.getEventValue() != 0D) {
          setEventValue(other.getEventValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        Ingest.EventData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Ingest.EventData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object eventType_ = "";
      /**
       * <code>string eventType = 1;</code>
       */
      public String getEventType() {
        Object ref = eventType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          eventType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string eventType = 1;</code>
       */
      public com.google.protobuf.ByteString
      getEventTypeBytes() {
        Object ref = eventType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (String) ref);
          eventType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string eventType = 1;</code>
       */
      public Builder setEventType(
              String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        eventType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string eventType = 1;</code>
       */
      public Builder clearEventType() {

        eventType_ = getDefaultInstance().getEventType();
        onChanged();
        return this;
      }
      /**
       * <code>string eventType = 1;</code>
       */
      public Builder setEventTypeBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        eventType_ = value;
        onChanged();
        return this;
      }

      private double eventValue_ ;
      /**
       * <code>double eventValue = 2;</code>
       */
      public double getEventValue() {
        return eventValue_;
      }
      /**
       * <code>double eventValue = 2;</code>
       */
      public Builder setEventValue(double value) {

        eventValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double eventValue = 2;</code>
       */
      public Builder clearEventValue() {

        eventValue_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:EventData)
    }

    // @@protoc_insertion_point(class_scope:EventData)
    private static final Ingest.EventData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Ingest.EventData();
    }

    public static Ingest.EventData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EventData>
            PARSER = new com.google.protobuf.AbstractParser<EventData>() {
      public EventData parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new EventData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EventData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<EventData> getParserForType() {
      return PARSER;
    }

    public Ingest.EventData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface InputEventProtoOrBuilder extends
          // @@protoc_insertion_point(interface_extends:InputEventProto)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 time = 1;</code>
     */
    long getTime();

    /**
     * <code>string vehicleId = 2;</code>
     */
    String getVehicleId();
    /**
     * <code>string vehicleId = 2;</code>
     */
    com.google.protobuf.ByteString
    getVehicleIdBytes();

    /**
     * <code>double lat = 3;</code>
     */
    double getLat();

    /**
     * <code>double lon = 4;</code>
     */
    double getLon();

    /**
     * <code>repeated .EventData eventData = 5;</code>
     */
    java.util.List<EventData>
    getEventDataList();
    /**
     * <code>repeated .EventData eventData = 5;</code>
     */
    Ingest.EventData getEventData(int index);
    /**
     * <code>repeated .EventData eventData = 5;</code>
     */
    int getEventDataCount();
    /**
     * <code>repeated .EventData eventData = 5;</code>
     */
    java.util.List<? extends EventDataOrBuilder>
    getEventDataOrBuilderList();
    /**
     * <code>repeated .EventData eventData = 5;</code>
     */
    Ingest.EventDataOrBuilder getEventDataOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code InputEventProto}
   */
  public  static final class InputEventProto extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:InputEventProto)
          InputEventProtoOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use InputEventProto.newBuilder() to construct.
    private InputEventProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InputEventProto() {
      time_ = 0L;
      vehicleId_ = "";
      lat_ = 0D;
      lon_ = 0D;
      eventData_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InputEventProto(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                      input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              time_ = input.readUInt64();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              vehicleId_ = s;
              break;
            }
            case 25: {

              lat_ = input.readDouble();
              break;
            }
            case 33: {

              lon_ = input.readDouble();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                eventData_ = new java.util.ArrayList<EventData>();
                mutable_bitField0_ |= 0x00000010;
              }
              eventData_.add(
                      input.readMessage(Ingest.EventData.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          eventData_ = java.util.Collections.unmodifiableList(eventData_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return Ingest.internal_static_InputEventProto_descriptor;
    }

    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
      return Ingest.internal_static_InputEventProto_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      Ingest.InputEventProto.class, Ingest.InputEventProto.Builder.class);
    }

    private int bitField0_;
    public static final int TIME_FIELD_NUMBER = 1;
    private long time_;
    /**
     * <code>uint64 time = 1;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int VEHICLEID_FIELD_NUMBER = 2;
    private volatile Object vehicleId_;
    /**
     * <code>string vehicleId = 2;</code>
     */
    public String getVehicleId() {
      Object ref = vehicleId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        vehicleId_ = s;
        return s;
      }
    }
    /**
     * <code>string vehicleId = 2;</code>
     */
    public com.google.protobuf.ByteString
    getVehicleIdBytes() {
      Object ref = vehicleId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        vehicleId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAT_FIELD_NUMBER = 3;
    private double lat_;
    /**
     * <code>double lat = 3;</code>
     */
    public double getLat() {
      return lat_;
    }

    public static final int LON_FIELD_NUMBER = 4;
    private double lon_;
    /**
     * <code>double lon = 4;</code>
     */
    public double getLon() {
      return lon_;
    }

    public static final int EVENTDATA_FIELD_NUMBER = 5;
    private java.util.List<EventData> eventData_;
    /**
     * <code>repeated .EventData eventData = 5;</code>
     */
    public java.util.List<EventData> getEventDataList() {
      return eventData_;
    }
    /**
     * <code>repeated .EventData eventData = 5;</code>
     */
    public java.util.List<? extends EventDataOrBuilder>
    getEventDataOrBuilderList() {
      return eventData_;
    }
    /**
     * <code>repeated .EventData eventData = 5;</code>
     */
    public int getEventDataCount() {
      return eventData_.size();
    }
    /**
     * <code>repeated .EventData eventData = 5;</code>
     */
    public Ingest.EventData getEventData(int index) {
      return eventData_.get(index);
    }
    /**
     * <code>repeated .EventData eventData = 5;</code>
     */
    public Ingest.EventDataOrBuilder getEventDataOrBuilder(
            int index) {
      return eventData_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (time_ != 0L) {
        output.writeUInt64(1, time_);
      }
      if (!getVehicleIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, vehicleId_);
      }
      if (lat_ != 0D) {
        output.writeDouble(3, lat_);
      }
      if (lon_ != 0D) {
        output.writeDouble(4, lon_);
      }
      for (int i = 0; i < eventData_.size(); i++) {
        output.writeMessage(5, eventData_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeUInt64Size(1, time_);
      }
      if (!getVehicleIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, vehicleId_);
      }
      if (lat_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
                .computeDoubleSize(3, lat_);
      }
      if (lon_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
                .computeDoubleSize(4, lon_);
      }
      for (int i = 0; i < eventData_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(5, eventData_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof Ingest.InputEventProto)) {
        return super.equals(obj);
      }
      Ingest.InputEventProto other = (Ingest.InputEventProto) obj;

      boolean result = true;
      result = result && (getTime()
              == other.getTime());
      result = result && getVehicleId()
              .equals(other.getVehicleId());
      result = result && (
              Double.doubleToLongBits(getLat())
                      == Double.doubleToLongBits(
                      other.getLat()));
      result = result && (
              Double.doubleToLongBits(getLon())
                      == Double.doubleToLongBits(
                      other.getLon()));
      result = result && getEventDataList()
              .equals(other.getEventDataList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getTime());
      hash = (37 * hash) + VEHICLEID_FIELD_NUMBER;
      hash = (53 * hash) + getVehicleId().hashCode();
      hash = (37 * hash) + LAT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              Double.doubleToLongBits(getLat()));
      hash = (37 * hash) + LON_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              Double.doubleToLongBits(getLon()));
      if (getEventDataCount() > 0) {
        hash = (37 * hash) + EVENTDATA_FIELD_NUMBER;
        hash = (53 * hash) + getEventDataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Ingest.InputEventProto parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Ingest.InputEventProto parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Ingest.InputEventProto parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Ingest.InputEventProto parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Ingest.InputEventProto parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Ingest.InputEventProto parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Ingest.InputEventProto parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static Ingest.InputEventProto parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Ingest.InputEventProto parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }
    public static Ingest.InputEventProto parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Ingest.InputEventProto parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static Ingest.InputEventProto parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Ingest.InputEventProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code InputEventProto}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:InputEventProto)
            Ingest.InputEventProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return Ingest.internal_static_InputEventProto_descriptor;
      }

      protected FieldAccessorTable
      internalGetFieldAccessorTable() {
        return Ingest.internal_static_InputEventProto_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        Ingest.InputEventProto.class, Ingest.InputEventProto.Builder.class);
      }

      // Construct using Ingest.InputEventProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEventDataFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        time_ = 0L;

        vehicleId_ = "";

        lat_ = 0D;

        lon_ = 0D;

        if (eventDataBuilder_ == null) {
          eventData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          eventDataBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return Ingest.internal_static_InputEventProto_descriptor;
      }

      public Ingest.InputEventProto getDefaultInstanceForType() {
        return Ingest.InputEventProto.getDefaultInstance();
      }

      public Ingest.InputEventProto build() {
        Ingest.InputEventProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Ingest.InputEventProto buildPartial() {
        Ingest.InputEventProto result = new Ingest.InputEventProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.time_ = time_;
        result.vehicleId_ = vehicleId_;
        result.lat_ = lat_;
        result.lon_ = lon_;
        if (eventDataBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            eventData_ = java.util.Collections.unmodifiableList(eventData_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.eventData_ = eventData_;
        } else {
          result.eventData_ = eventDataBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Ingest.InputEventProto) {
          return mergeFrom((Ingest.InputEventProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Ingest.InputEventProto other) {
        if (other == Ingest.InputEventProto.getDefaultInstance()) return this;
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (!other.getVehicleId().isEmpty()) {
          vehicleId_ = other.vehicleId_;
          onChanged();
        }
        if (other.getLat() != 0D) {
          setLat(other.getLat());
        }
        if (other.getLon() != 0D) {
          setLon(other.getLon());
        }
        if (eventDataBuilder_ == null) {
          if (!other.eventData_.isEmpty()) {
            if (eventData_.isEmpty()) {
              eventData_ = other.eventData_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureEventDataIsMutable();
              eventData_.addAll(other.eventData_);
            }
            onChanged();
          }
        } else {
          if (!other.eventData_.isEmpty()) {
            if (eventDataBuilder_.isEmpty()) {
              eventDataBuilder_.dispose();
              eventDataBuilder_ = null;
              eventData_ = other.eventData_;
              bitField0_ = (bitField0_ & ~0x00000010);
              eventDataBuilder_ =
                      com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                              getEventDataFieldBuilder() : null;
            } else {
              eventDataBuilder_.addAllMessages(other.eventData_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        Ingest.InputEventProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Ingest.InputEventProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long time_ ;
      /**
       * <code>uint64 time = 1;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>uint64 time = 1;</code>
       */
      public Builder setTime(long value) {

        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 time = 1;</code>
       */
      public Builder clearTime() {

        time_ = 0L;
        onChanged();
        return this;
      }

      private Object vehicleId_ = "";
      /**
       * <code>string vehicleId = 2;</code>
       */
      public String getVehicleId() {
        Object ref = vehicleId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          vehicleId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string vehicleId = 2;</code>
       */
      public com.google.protobuf.ByteString
      getVehicleIdBytes() {
        Object ref = vehicleId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (String) ref);
          vehicleId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string vehicleId = 2;</code>
       */
      public Builder setVehicleId(
              String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        vehicleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string vehicleId = 2;</code>
       */
      public Builder clearVehicleId() {

        vehicleId_ = getDefaultInstance().getVehicleId();
        onChanged();
        return this;
      }
      /**
       * <code>string vehicleId = 2;</code>
       */
      public Builder setVehicleIdBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        vehicleId_ = value;
        onChanged();
        return this;
      }

      private double lat_ ;
      /**
       * <code>double lat = 3;</code>
       */
      public double getLat() {
        return lat_;
      }
      /**
       * <code>double lat = 3;</code>
       */
      public Builder setLat(double value) {

        lat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double lat = 3;</code>
       */
      public Builder clearLat() {

        lat_ = 0D;
        onChanged();
        return this;
      }

      private double lon_ ;
      /**
       * <code>double lon = 4;</code>
       */
      public double getLon() {
        return lon_;
      }
      /**
       * <code>double lon = 4;</code>
       */
      public Builder setLon(double value) {

        lon_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double lon = 4;</code>
       */
      public Builder clearLon() {

        lon_ = 0D;
        onChanged();
        return this;
      }

      private java.util.List<EventData> eventData_ =
              java.util.Collections.emptyList();
      private void ensureEventDataIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          eventData_ = new java.util.ArrayList<EventData>(eventData_);
          bitField0_ |= 0x00000010;
        }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
              EventData, EventData.Builder, EventDataOrBuilder> eventDataBuilder_;

      /**
       * <code>repeated .EventData eventData = 5;</code>
       */
      public java.util.List<EventData> getEventDataList() {
        if (eventDataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(eventData_);
        } else {
          return eventDataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .EventData eventData = 5;</code>
       */
      public int getEventDataCount() {
        if (eventDataBuilder_ == null) {
          return eventData_.size();
        } else {
          return eventDataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .EventData eventData = 5;</code>
       */
      public Ingest.EventData getEventData(int index) {
        if (eventDataBuilder_ == null) {
          return eventData_.get(index);
        } else {
          return eventDataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .EventData eventData = 5;</code>
       */
      public Builder setEventData(
              int index, Ingest.EventData value) {
        if (eventDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventDataIsMutable();
          eventData_.set(index, value);
          onChanged();
        } else {
          eventDataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .EventData eventData = 5;</code>
       */
      public Builder setEventData(
              int index, Ingest.EventData.Builder builderForValue) {
        if (eventDataBuilder_ == null) {
          ensureEventDataIsMutable();
          eventData_.set(index, builderForValue.build());
          onChanged();
        } else {
          eventDataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .EventData eventData = 5;</code>
       */
      public Builder addEventData(Ingest.EventData value) {
        if (eventDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventDataIsMutable();
          eventData_.add(value);
          onChanged();
        } else {
          eventDataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .EventData eventData = 5;</code>
       */
      public Builder addEventData(
              int index, Ingest.EventData value) {
        if (eventDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventDataIsMutable();
          eventData_.add(index, value);
          onChanged();
        } else {
          eventDataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .EventData eventData = 5;</code>
       */
      public Builder addEventData(
              Ingest.EventData.Builder builderForValue) {
        if (eventDataBuilder_ == null) {
          ensureEventDataIsMutable();
          eventData_.add(builderForValue.build());
          onChanged();
        } else {
          eventDataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .EventData eventData = 5;</code>
       */
      public Builder addEventData(
              int index, Ingest.EventData.Builder builderForValue) {
        if (eventDataBuilder_ == null) {
          ensureEventDataIsMutable();
          eventData_.add(index, builderForValue.build());
          onChanged();
        } else {
          eventDataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .EventData eventData = 5;</code>
       */
      public Builder addAllEventData(
              Iterable<? extends EventData> values) {
        if (eventDataBuilder_ == null) {
          ensureEventDataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
                  values, eventData_);
          onChanged();
        } else {
          eventDataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .EventData eventData = 5;</code>
       */
      public Builder clearEventData() {
        if (eventDataBuilder_ == null) {
          eventData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          eventDataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .EventData eventData = 5;</code>
       */
      public Builder removeEventData(int index) {
        if (eventDataBuilder_ == null) {
          ensureEventDataIsMutable();
          eventData_.remove(index);
          onChanged();
        } else {
          eventDataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .EventData eventData = 5;</code>
       */
      public Ingest.EventData.Builder getEventDataBuilder(
              int index) {
        return getEventDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .EventData eventData = 5;</code>
       */
      public Ingest.EventDataOrBuilder getEventDataOrBuilder(
              int index) {
        if (eventDataBuilder_ == null) {
          return eventData_.get(index);  } else {
          return eventDataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .EventData eventData = 5;</code>
       */
      public java.util.List<? extends EventDataOrBuilder>
      getEventDataOrBuilderList() {
        if (eventDataBuilder_ != null) {
          return eventDataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(eventData_);
        }
      }
      /**
       * <code>repeated .EventData eventData = 5;</code>
       */
      public Ingest.EventData.Builder addEventDataBuilder() {
        return getEventDataFieldBuilder().addBuilder(
                Ingest.EventData.getDefaultInstance());
      }
      /**
       * <code>repeated .EventData eventData = 5;</code>
       */
      public Ingest.EventData.Builder addEventDataBuilder(
              int index) {
        return getEventDataFieldBuilder().addBuilder(
                index, Ingest.EventData.getDefaultInstance());
      }
      /**
       * <code>repeated .EventData eventData = 5;</code>
       */
      public java.util.List<EventData.Builder>
      getEventDataBuilderList() {
        return getEventDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
              EventData, EventData.Builder, EventDataOrBuilder>
      getEventDataFieldBuilder() {
        if (eventDataBuilder_ == null) {
          eventDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                  EventData, EventData.Builder, EventDataOrBuilder>(
                  eventData_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          eventData_ = null;
        }
        return eventDataBuilder_;
      }
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:InputEventProto)
    }

    // @@protoc_insertion_point(class_scope:InputEventProto)
    private static final Ingest.InputEventProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Ingest.InputEventProto();
    }

    public static Ingest.InputEventProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InputEventProto>
            PARSER = new com.google.protobuf.AbstractParser<InputEventProto>() {
      public InputEventProto parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new InputEventProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InputEventProto> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<InputEventProto> getParserForType() {
      return PARSER;
    }

    public Ingest.InputEventProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_EventData_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_EventData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_InputEventProto_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_InputEventProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
          descriptor;
  static {
    String[] descriptorData = {
            "\n\014ingest.proto\"2\n\tEventData\022\021\n\teventType" +
                    "\030\001 \001(\t\022\022\n\neventValue\030\002 \001(\001\"k\n\017InputEvent" +
                    "Proto\022\014\n\004time\030\001 \001(\004\022\021\n\tvehicleId\030\002 \001(\t\022\013" +
                    "\n\003lat\030\003 \001(\001\022\013\n\003lon\030\004 \001(\001\022\035\n\teventData\030\005 " +
                    "\003(\0132\n.EventDatab\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
              public com.google.protobuf.ExtensionRegistry assignDescriptors(
                      com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
              }
            };
    com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[] {
                    }, assigner);
    internal_static_EventData_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_EventData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_EventData_descriptor,
            new String[] { "EventType", "EventValue", });
    internal_static_InputEventProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
    internal_static_InputEventProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_InputEventProto_descriptor,
            new String[] { "Time", "VehicleId", "Lat", "Lon", "EventData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
